In [10]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error, r2_score

In [3]:
data=pd.read_excel('data.xlsx')

In [7]:
data.describe()

,Invoice ID,Customer ID,Total,Quantity,Item Total,Item Price,Product ID,Month,Year
count,2.104410e+05,2.104410e+05,210441.000000,210441.000000,210441.000000,210441.000000,2.104410e+05,210441.000000,210441.000000
mean,2.097920e+17,2.097920e+17,4215.576552,4.708692,209.372394,65.752160,2.097920e+17,7.921284,2021.054224
std,1.398180e+07,6.552464e+06,10914.112276,20.567158,916.002325,50.450605,1.035516e+06,3.356840,0.230206
min,2.097920e+17,2.097920e+17,14.500000,0.020000,0.000000,0.000000,2.097920e+17,1.000000,2021.000000
25%,2.097920e+17,2.097920e+17,1013.000000,0.600000,34.500000,33.000000,2.097920e+17,5.000000,2021.000000
50%,2.097920e+17,2.097920e+17,1747.700000,1.000000,72.000000,54.000000,2.097920e+17,9.000000,2021.000000
75%,2.097920e+17,2.097920e+17,3167.900000,3.000000,160.000000,83.000000,2.097920e+17,11.000000,2021.000000
max,2.097920e+17,2.097920e+17,172028.600000,951.000000,92460.000000,1600.000000,2.097920e+17,12.000000,2023.000000

In [11]:
X = data[['Month','Item Price','Item Total']]
y = data['Quantity'] 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeRegressor()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Evaluate mean squared error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# Evaluate mean absolute error
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

# Evaluate R-squared
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

Mean Squared Error: 5.421143666796023
Mean Absolute Error: 0.10823979345355488
R-squared: 0.9868419820571627

In [16]:
X = data[['Total','Quantity','Item Total']]
y = data['Item Price'] 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeRegressor()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Evaluate mean squared error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# Evaluate mean absolute error
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

# Evaluate R-squared
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

Mean Squared Error: 2.3447969205466985
Mean Absolute Error: 0.14742965382879314
R-squared: 0.999090841623724