In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats

In [2]:
df = pd.read_csv(r'C:\Users\IT RENTAL\Documents\New folder\invoice 2023.csv', low_memory=False )

In [3]:
df

,Invoice ID,Invoice Status,Customer ID,Due Date,Total,Last Payment Date,Item Name,Quantity,Item Total,Item Price,Product ID,SKU,Customer Name,Invoice Date,Invoice Number,Account,Item Type,Usage Unit,Invoice Month
0,2.097920e+17,Closed,2.097920e+17,01-01-2023,12394.5,27-01-2023,"Tomato Hybrid (Mix of medium, semi ripe 12-16 ...",100.0,1400.0,14.0,2.10E+17,FARMTHFINALCAT107,KINEMATIC FOODTECH PRIVATE LIMITED,01-01-2023,INV-082845,Sales,goods,1 Kg,January
1,2.097920e+17,Closed,2.097920e+17,01-01-2023,12394.5,27-01-2023,"Potato - (Medium, 17-20 pcs/kg)",50.0,1350.0,27.0,2.10E+17,FARMTHFINALCAT94,KINEMATIC FOODTECH PRIVATE LIMITED,01-01-2023,INV-082845,Sales,goods,1 Kg,January
2,2.097920e+17,Closed,2.097920e+17,01-01-2023,12394.5,27-01-2023,Onion - Medium,100.0,2500.0,25.0,2.10E+17,FARMTHFINALCAT82,KINEMATIC FOODTECH PRIVATE LIMITED,01-01-2023,INV-082845,Sales,goods,1 Kg,January
3,2.097920e+17,Closed,2.097920e+17,01-01-2023,12394.5,27-01-2023,"Cucumber Indian (Big, misshapes)",50.0,600.0,12.0,2.10E+17,FARMTHFINALCAT54,KINEMATIC FOODTECH PRIVATE LIMITED,01-01-2023,INV-082845,Sales,goods,1 Kg,January
4,2.097920e+17,Closed,2.097920e+17,01-01-2023,12394.5,27-01-2023,curry leaves,2.0,150.0,75.0,2.10E+17,FARMTHFINALCAT57,KINEMATIC FOODTECH PRIVATE LIMITED,01-01-2023,INV-082845,Sales,goods,Kg,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693355,2.097920e+17,Open,2.097920e+17,30-06-2023,549.0,NaN,Mango Ripe,1.0,80.0,80.0,2.10E+17,FARMTHFINALCAT33238,RED APPLE KITCHEN CONSULTANCY PVT LTD (COLLAGE...,04-06-2023,INV-121927,Sales,goods,1 Kg,June
693356,2.097920e+17,Open,2.097920e+17,30-06-2023,549.0,NaN,Lettuce Iceberg,0.6,54.0,90.0,2.10E+17,FARMTHFINALCAT74,RED APPLE KITCHEN CONSULTANCY PVT LTD (COLLAGE...,04-06-2023,INV-121927,Sales,goods,1 Kg,June
693357,2.097920e+17,Open,2.097920e+17,30-06-2023,549.0,NaN,Lettuce Green,0.5,82.5,165.0,2.10E+17,FARMTHFINALCAT73,RED APPLE KITCHEN CONSULTANCY PVT LTD (COLLAGE...,04-06-2023,INV-121927,Sales,goods,1 Kg,June
693358,2.097920e+17,Open,2.097920e+17,30-06-2023,549.0,NaN,Lettuce Romaine,0.5,65.0,130.0,2.10E+17,FARMTHFINALCAT76,RED APPLE KITCHEN CONSULTANCY PVT LTD (COLLAGE...,04-06-2023,INV-121927,Sales,goods,1 Kg,June
693359,2.097920e+17,Open,2.097920e+17,30-06-2023,549.0,NaN,Rocket Lettuce - Arugula,0.5,52.5,105.0,2.10E+17,FARMTHFINALCAT99370,RED APPLE KITCHEN CONSULTANCY PVT LTD (COLLAGE...,04-06-2023,INV-121927,Sales,goods,1 Kg,June

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 693360 entries, 0 to 693359
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Invoice ID         693360 non-null  float64
 1   Invoice Status     693360 non-null  object
 2   Customer ID        693360 non-null  float64
 3   Due Date           693360 non-null  object
 4   Total              693360 non-null  float64
 5   Last Payment Date  572071 non-null  object
 6   Item Name          693360 non-null  object
 7   Quantity           693360 non-null  float64
 8   Item Total         693360 non-null  float64
 9   Item Price         693360 non-null  float64
 10  Product ID         693360 non-null  object
 11  SKU                693360 non-null  object
 12  Customer Name      693360 non-null  object
 13  Invoice Date       693360 non-null  object
 14  Invoice Number     693360 non-null  object
 15  Account            693360 non-null  object
 16  Item Type          693360 non-null  object
 17  Usage Unit         693360 non-null  object
 18  Invoice Month      693360 non-null  object
dtypes: float64(6), object(13)
memory usage: 100.5+ MB

In [9]:
quantity = df['Quantity']
Item_Price = df['Item Price']

# Perform the KS test
ks_statistic, p_value = stats.ks_2samp(quantity, Item_Price)

# Print the KS test statistics and p-value
print("KS statistic:", ks_statistic)
print("P-Value:", p_value)

KS statistic: 0.9407046844352139
P-Value: 0.0

In [11]:
total = df['Total']
item_total = df['Item Total']

# Perform the KS test
ks_statistic, p_value = stats.ks_2samp(total, item_total)

# Print the KS test statistics and p-value
print("KS statistic:", ks_statistic)
print("P-Value:", p_value)

KS statistic: 0.9697199146186685
P-Value: 0.0